[build]
  base = "."
  publish = "."
  command = "echo 'Static site'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"  
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  from = "/roi-calculator"
  to = "/roi-calculator-optimized.html"
  status = 200

[[redirects]]
  from = "/ab-testing"
  to = "/ab-testing-tracker-optimized.html"
  status = 200

[[redirects]]
  from = "/linkedin-profile"
  to = "/linkedin-profile-mockup-optimized.html" 
  status = 200

[[redirects]]
  from = "/naming-dashboard"
  to = "/naming-dashboard-optimized.html"
  status = 200

[[redirects]]
  from = "/decision-matrix"
  to = "/decision-matrix-optimized.html"
  status = 200

[[redirects]]
  from = "/whatsapp"
  to = "https://wa.me/5511999999999?text=Oi!%20Quero%20saber%20mais%20sobre%20o%20Sprint"
  status = 302
