name: "Product/Market Analysis"
agents: 5
questions:
  - "What is the market size, growth rate, and competitive landscape?"
  - "Who are the target users, what are their needs, and how well are they being served?"
  - "What are the technical capabilities, limitations, and differentiation factors?"
  - "What are the business model, pricing strategies, and path to profitability?"
  - "What are the risks, challenges, and potential disruption scenarios?"
roles:
  - "Market Analysis"
  - "User Research"
  - "Technical Assessment"
  - "Business Strategy"
  - "Risk Analysis"
